### ISSUE TITLE
Implement Prometheus Metrics for Nauticus controller

### ISSUE THREAD

**Issue by smileisak** [edixos/Nauticus#16]
The goal of this task is to implement Prometheus metrics for the Nauticus controller. This will involve creating new endpoints in the controller to expose metrics in a Prometheus-compatible format and configuring Prometheus to scrape these endpoints. The metrics should include information about the number of spaces, resource quotas, and network policies created, updated, and deleted. Additionally, it should include information about the number of errors that occur during these operations. The implementation should follow best practices for Prometheus metric collection and should be thoroughly tested before being merged into the main codebase. A documentation should be added to the official documentation of nauticus about how to use these metrics. The task should also include the setup of grafana dashboard for the metrics.

**Comment by sftim** [comment]
BTW, we might want to specify [OpenMetrics](https://openmetrics.io/) format rather than Prometheus. Prometheus' de facto text format evolved into OpenMetrics.
