### ISSUE TITLE
Add annotation to ignore underlying resource deletion.

### ISSUE THREAD

**Issue by smileisak** [edixos/Nauticus#9]
Objective: To add the ability for users to specify that resources created in a Space should not be deleted when the Space is deleted.

Steps:

- [x] Add an annotation "nauticus.io/ignore-deletion" to the Space CRD.
- [x] Update the Nauticus controller code to check for this annotation when a Space is deleted.
- [x] If the annotation is present, update the owner references of all resources within the Space to remove the Space as the owner. This will prevent Kubernetes from automatically deleting the resources when the Space is deleted.
- [ ] Create a field in the Space CRD that allow users to specify a grace period before the controller deletes the resources.
- [ ] Modify the controller to delete all resources in the space after the grace period, this will allow the users to drain their resources before they are deleted.
- [x] Test the new feature by creating a Space and adding resources, then deleting the Space and verifying that the resources are not deleted automatically and the controller deletes them after the grace period.
- [x] Document the new feature in the README and update the user documentation accordingly.

## References

- https://kubernetes.io/docs/concepts/architecture/garbage-collection/
- https://kubernetes.io/docs/tasks/administer-cluster/use-cascading-deletion/#use-background-cascading-deletion
- https://kubernetes.io/docs/tasks/administer-cluster/use-cascading-deletion/

**Comment by sftim** [comment]
Does this annotation also affect finalizers on the Namespace for the Space?

**Comment by smileisak** [comment]
@sftim I don't think so, today we have a lightweight finalizer in the `Space` controller to manage the deletion of the `Space` resource.

We should find a way to update the controller so it can ignores the underlying managed resources when a specific annotation is present. Something equivalent to Google Config Connector deletion policy. 

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/6867b8385179bc1e09fe21aa20c58a31f6f8b9bc/pkg/controller/deletiondefender/controller.go#L126-L131
